---
# tasks file for elasticsearch

- name: Assures Java installed (Elasticsearch dependency)
  yum: name={{ java_version}} state=present

- name: Add Elasticsearch GPG key.
  rpm_key:
    key: http://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository.
  template:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: 0644

- name: Install Elasticsearch.
  yum: name=elasticsearch state=present

- name: Configure Elasticsearch.
  lineinfile:
    dest: /etc/elasticsearch/elasticsearch.yml
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: '^#?network\.host', line: 'network.host: {{ es_network.host}}' }
    - { regexp: '^#?index\.number_of_shards:', line: 'index.number_of_shards: {{ es_index.number_of_shards }}' }
    - { regexp: '^#?index\.number_of_replicas:', line: 'index.number_of_replicas: {{es_index.number_of_replicas }}' }
  notify: restart elasticsearch

- name: change Elastic Search Heap size to {{ es_heap_size }}
  lineinfile:
      dest: /etc/sysconfig/elasticsearch
      regexp: "^#?ES_HEAP_SIZE"
      line: "ES_HEAP_SIZE={{ es_heap_size }}"
  notify: restart elasticsearch

- name: Copy Xenforo ES scripts to /etc/elasticsearch/scripts/
  when: xenforo
  copy:
    src: XenforoES/
    dest: /etc/elasticsearch/scripts/
  notify: restart elasticsearch

- name: Start Elasticsearch.
  service: name=elasticsearch.service state=started enabled=yes
